<a href="https://colab.research.google.com/github/karishmasd/Neural_Networks/blob/main/Broad_casting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Calories from  Carbs ,Protiens ,fats in 100gms of different foods

In [5]:
Apples =[56,1.2,1.8]
Beef=[0,104.0,135.0]
Eggs=[4.4,52.0,99.0]
Potatoes=[68.0,8.0,0.9]
calories=(np.array([Apples,Beef,Eggs,Potatoes])).T
calories

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

Calculate the percentage of calories from carbs , protein and fats from each food

In [15]:
Weight=100
sum=np.sum(calories,axis=0)
percentage_of_calories = (calories/(sum))*Weight
#broadcasting:here python has automatically used the weight as 4*1 matrix to  the element wise division
percentage_of_calories


array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [19]:
PERCENTAGE=Weight*calories/sum.reshape(1,4)
PERCENTAGE

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

#Other examples of broad casting

In [25]:
A=[1,2,3]
b=[100,100,100]
c=100
A+b
#this happened beacuase python took them as list

[1, 2, 3, 100, 100, 100]

In [27]:
A=np.array([1,2,3])
b=np.array([100,100,100])
c=100
print(A+b)
A+c

[101 102 103]


array([101, 102, 103])

In [29]:
A=np.array([[1,2,3],[1,2,3]])
print(A+b)
print(A+c)

[[101 102 103]
 [101 102 103]]
[[101 102 103]
 [101 102 103]]


In [36]:
d=np.array([[50],[100]])
print(A+d)

[[ 51  52  53]
 [101 102 103]]
