<a href="https://colab.research.google.com/github/karishmasd/Neural_Networks/blob/main/Broad_casting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Calories from  Carbs ,Protiens ,fats in 100gms of different foods

In [ ]:
Apples =[56,1.2,1.8]
Beef=[0,104.0,135.0]
Eggs=[4.4,52.0,99.0]
Potatoes=[68.0,8.0,0.9]
calories=(np.array([Apples,Beef,Eggs,Potatoes])).T
calories

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

Calculate the percentage of calories from carbs , protein and fats from each food

In [ ]:
Weight=100
sum=np.sum(calories,axis=0)
percentage_of_calories = (calories/(sum))*Weight
#broadcasting:here python has automatically used the weight as 4*1 matrix to  the element wise division
percentage_of_calories


array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [ ]:
PERCENTAGE=Weight*calories/sum.reshape(1,4)
PERCENTAGE

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

#Other examples of broad casting

In [ ]:
A=[1,2,3]
b=[100,100,100]
c=100
A+b
#this happened beacuase python took them as list

[1, 2, 3, 100, 100, 100]

In [ ]:
A=np.array([1,2,3])
b=np.array([100,100,100])
c=100
print(A+b)
A+c

[101 102 103]


array([101, 102, 103])

In [ ]:
A=np.array([[1,2,3],[1,2,3]])
print(A+b)
print(A+c)

[[101 102 103]
 [101 102 103]]
[[101 102 103]
 [101 102 103]]


In [ ]:
d=np.array([[50],[100]])
print(A+d)

[[ 51  52  53]
 [101 102 103]]


#A note on nympy vectors

In [46]:
#Never use rank 1 arrays
#if when ever you are ended up with this kind of rank 1 array you can reshape them as either (5,1) or (1,5)
A=np.random.randn(5)
print(np.shape(A),"This is called rank 1 array doesnot behave like a row vector or a column vector ")
print(np.shape(A.T))
print(A)
print(np.dot(A,A.T))

(5,) This is called rank 1 array doesnot behave like a row vector or a column vector 
(5,)
[-0.52077288 -0.14903774  1.20048099 -0.64267412  0.12375634]
2.1629169048926205


In [48]:
#Use Column or Row vectors
A=np.random.randn(5,1)
print(np.shape(A),"This is a column vector" )
print(A)
print(np.dot(A,A.T))

(5, 1) This is a column vector
[[ 0.65472319]
 [ 0.1537114 ]
 [ 0.09194367]
 [-1.3113728 ]
 [-0.14377209]]
[[ 0.42866246  0.10063842  0.06019765 -0.85858619 -0.09413092]
 [ 0.10063842  0.02362719  0.01413279 -0.20157295 -0.02209941]
 [ 0.06019765  0.01413279  0.00845364 -0.12057243 -0.01321893]
 [-0.85858619 -0.20157295 -0.12057243  1.71969863  0.18853881]
 [-0.09413092 -0.02209941 -0.01321893  0.18853881  0.02067041]]
