<a href="https://colab.research.google.com/github/karishmasd/Neural_Networks/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Logistic Regression with a Neural Network mindset



In [4]:
import numpy as np


In [5]:
def sigmoid(z):
  s=1/(1+np.exp(-z))
  return s

In [8]:
print(str(sigmoid(np.array([0,2]))))

[0.5        0.88079708]


In [10]:
z= np.array([1,3,5,7])
sigmoid(z)

array([0.73105858, 0.95257413, 0.99330715, 0.99908895])

intitalizing parameters (w,b)

In [12]:
def initialize_with_zeros(dim):
  w=np.zeros((dim,1))
  b=0.00
  return w,b

In [16]:
dim=10
initialize_with_zeros(dim)

(array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 0.0)

In [24]:
def propagate(w,b,X,Y):
  m=100 #no of training examples that is X (nump_x*nump_x*3,m )
  A=sigmoid(np.dot(w.T,X)+b)
  #Cost function
  J=(-1/m)*(Y*np.log(A)+(1-Y)*np.log(1-A))
  dw=(1/m)*np.dot(X,(A-Y).T)
  db=(1/m)* np.sum(A-Y)
  Cost=J
  grads= {"dw":dw,"db":db}
  return grads,Cost

In [26]:
w =  np.array([[1.], [2]])
b = 1.5

# X is using 3 examples, with 2 features each
# Each example is stacked column-wise
X = np.array([[1., -2., -1.], [3., 0.5, -3.2]])
Y = np.array([[1, 1, 0]])
propagate(w, b, X, Y)

({'dw': array([[ 0.00752146],
         [-0.00198123]]),
  'db': -0.003750121350131895},
 array([[2.03447672e-06, 4.74076984e-03, 2.73569938e-05]]))

Optimization

In [62]:
def optimize(w, b, X, Y, num_iterations, learning_rate, print_Cost=False):
  Costs = []
  for i in range(num_iterations):
    grads, Cost = propagate(w, b, X, Y)
    dw = grads["dw"]
    db = grads["db"]
    w = w - learning_rate * dw
    b = b - learning_rate * db

    if i % 100 == 0:
      Costs.append(Cost)
      if print_Cost:
        print("Cost after iteration %i: %f" % (i, Cost))

  # Return statement moved outside the loop
  params = {"w": w, "b": b}
  grads = {"dw": dw, "db": db}
  return params, grads, Costs

In [66]:
optimize(w,b,X,Y,num_iterations=100,learning_rate=0.002,print_Cost=False)

({'w': array([[0.99849755],
         [2.00039579]]),
  'b': 1.5007491020135186},
 {'dw': array([[ 0.00750305],
         [-0.00197672]]),
  'db': -0.003740903956207224},
 [array([[2.03447672e-06, 4.74076984e-03, 2.73569938e-05]])])